---
#
# Use mode: 644 and group: root for key on bootstrap
#
secret_files:
  cert:
    path:  '/etc/pki/tls/certs/db01.bgo.uhdc.no.cert.pem'
    mode:  '0644'
    owner: 'root'
    group: 'root'
  key:
    path:  '/etc/pki/tls/private/db01.bgo.uhdc.no.key.pem'
    mode:  '0640'
#    mode:  '0644'
    owner: 'root'
    group: 'mysql'
#    group: 'root'
  cafile:
    path:  '/etc/pki/tls/certs/cachain.pem'
    mode:  '0644'
    owner: 'root'
    group: 'root'
